GET http://localhost:3001/subscribers

####

GET http://localhost:3001/subscribers

###

POST http://localhost:3001/subscribers
Content-Type: application/json

{
   "name" : "Ali Candan",
    "subscribedToChannel" : "KV Ilk 97"

},


###
DELETE http://localhost:3001/subscribers/6360231e6eca12f2f0491e7